- hosts: send-dotfiles
  remote_user: alex
  gather_facts: True
  tasks:
  - name: copy my dotfiles
    copy: src="../private/dotfiles/{{ item }}" dest=".{{ item }}"
    with_items:
    - vimrc
    - bashrc
    - bash_profile
    - screenrc
