- hosts: send-dotfiles
  remote_user: "{{ my_username }}"
  gather_facts: False
  tasks:
  - name: copy my dotfiles
    copy: src="../private/dotfiles/{{ item }}" dest="~{{ my_username }}/.{{ item }}"
    with_items:
    - vimrc
    - bashrc
    - bash_profile
    - screenrc
