- hosts: update-hosts
  tasks:
  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item.name }}$' line="{{ item.ip }} {{ item.name }} {{ item.short }}" state=present
    with_items: "{{ hosts_file }}"
