- hosts: update-hosts
  tasks:
  - name: "Removing hamachi entries"
    lineinfile: dest=/etc/hosts regexp='^25.' state=absent
  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts line="{{ item.ip }} {{ item.name }} {{ item.short }}" state=present
    with_items: "{{ hosts_file }}"
