- hosts: linux-root
  tasks:
  - name: "Build hosts file"
    lineinfile: dest=/etc/hosts regexp='.*{{ item.name }}$' line="{{ item.ip }} {{ item.name }} {{ item.short }}" state=present
    with_items: {{ host_files }}
